check:
    global:
        statements: 50 
        lines: 50
        branches: 50
        functions: 50
        excludes: []
#    each:
#        statements: 90
#        lines: 90
#        branches: 60
#        functions: 100
